apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  selector:
    app: ic-webapp  # Le sélecteur correspond aux pods que vous voulez exposer
  ports:
    - protocol: TCP
      port: 80       # Le port sur lequel le service est accessible depuis l'extérieur
      targetPort: 8080  # Le port sur lequel les pods écoutent
  type: NodePort     # Type de service pour utiliser NodePort
