apiVersion: v1
kind: Deployment
metadata:
  name: odoo-deployment
  labels:
    app: odoo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo:latest
        ports:
        - containerPort: 8069
        volumeMounts:
        - name: odoo-data
          mountPath: /var/lib/odoo
      volumes:
      - name: odoo-data
        persistentVolumeClaim:
          claimName: odoo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: odoo
spec:
  ports:
  - port: 8069
  selector:
    app: odoo
---
apiVersion: v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app: pgadmin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: pgadmin-config
          mountPath: /pgadmin4/servers.json
      volumes:
      - name: pgadmin-config
        configMap:
          name: pgadmin-config

